<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OO0DI5VI" failures="2" tests="4" name="Test" time="15.748" errors="0" timestamp="2025-09-19T23:14:16 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.674"/>
  <testcase classname="api.test.UserTests2" name="testGetUser" time="4.625">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUser(UserTests2.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests2" name="testUpdateUser" time="5.369">
    <failure type="java.lang.AssertionError" message="expected [Keven] but found [Shandra]">
      <![CDATA[java.lang.AssertionError: expected [Keven] but found [Shandra]
at api.test.UserTests2.testUpdateUser(UserTests2.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.test.UserTests2" name="testdeleteByName" time="2.49"/>
</testsuite> <!-- Test -->
